# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('urlImage', models.URLField(null=True)),
                ('publishedOn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, help_text=b'Designates if a user has confirmed his/her email.', verbose_name=b'Confirmation Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
