# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
