# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180405_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('sentenceNumber', models.IntegerField()),
                ('factURL', models.URLField()),
                ('similarityPercentage', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
    ]
