# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180416_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimentResult', models.CharField(max_length=100)),
            ],
        ),
    ]
