# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sentiment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='factcheck',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
            preserve_default=False,
        ),
    ]
