# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
