# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_factcheck_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='sentimentResult',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
