# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180416_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentiment',
        ),
        migrations.AddField(
            model_name='article',
            name='sentimentResult',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
