# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180417_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sourceID',
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factcheck',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
            preserve_default=False,
        ),
    ]
