# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180417_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('text', models.CharField(max_length=400)),
                ('url', models.URLField()),
                ('urlImage', models.URLField(null=True)),
                ('publishedOn', models.CharField(max_length=200)),
                ('sentimentNeg', models.CharField(max_length=100, null=True)),
                ('sentimentNeu', models.CharField(max_length=100, null=True)),
                ('sentimentPos', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
