# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180417_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='factcheck',
            name='sentence',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
