# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_searcharticle'),
        ('app', '0017_factcheck_sentence'),
    ]

    operations = [
    ]
