# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180501_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factcheck',
            name='URLFact',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
